# SPDX-FileCopyrightText: 2021 John Irle
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "src/**/__snapshots__/*.snap"
SPDX-FileCopyrightText = "2021 Your Name"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "public/robots.txt"
SPDX-FileCopyrightText = "2021 Your Name"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "*.json"
SPDX-FileCopyrightText = "2021 John Irle"
SPDX-License-Identifier = "MIT"
